/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CommunicationChannel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class CommunicationChannel {

  @JsonProperty("address")

  private String address = null;

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("position")

  private Integer position = null;

  @JsonProperty("type")

  private String type = null;

  @JsonProperty("user_id")

  private Integer userId = null;

  @JsonProperty("workflow_state")

  private String workflowState = null;
  public CommunicationChannel address(String address) {
    this.address = address;
    return this;
  }

  

  /**
  * The address, or path, of the communication channel.
  * @return address
  **/
  @Schema(example = "sheldon@caltech.example.com", description = "The address, or path, of the communication channel.")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }
  public CommunicationChannel id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * The ID of the communication channel.
  * @return id
  **/
  @Schema(example = "16", description = "The ID of the communication channel.")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public CommunicationChannel position(Integer position) {
    this.position = position;
    return this;
  }

  

  /**
  * The position of this communication channel relative to the user&#x27;s other channels when they are ordered.
  * @return position
  **/
  @Schema(example = "1", description = "The position of this communication channel relative to the user's other channels when they are ordered.")
  public Integer getPosition() {
    return position;
  }
  public void setPosition(Integer position) {
    this.position = position;
  }
  public CommunicationChannel type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * The type of communcation channel being described. Possible values are: &#x27;email&#x27;, &#x27;push&#x27;, &#x27;sms&#x27;, or &#x27;twitter&#x27;. This field determines the type of value seen in &#x27;address&#x27;.
  * @return type
  **/
  @Schema(example = "email", description = "The type of communcation channel being described. Possible values are: 'email', 'push', 'sms', or 'twitter'. This field determines the type of value seen in 'address'.")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  public CommunicationChannel userId(Integer userId) {
    this.userId = userId;
    return this;
  }

  

  /**
  * The ID of the user that owns this communication channel.
  * @return userId
  **/
  @Schema(example = "1", description = "The ID of the user that owns this communication channel.")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }
  public CommunicationChannel workflowState(String workflowState) {
    this.workflowState = workflowState;
    return this;
  }

  

  /**
  * The current state of the communication channel. Possible values are: &#x27;unconfirmed&#x27; or &#x27;active&#x27;.
  * @return workflowState
  **/
  @Schema(example = "active", description = "The current state of the communication channel. Possible values are: 'unconfirmed' or 'active'.")
  public String getWorkflowState() {
    return workflowState;
  }
  public void setWorkflowState(String workflowState) {
    this.workflowState = workflowState;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommunicationChannel communicationChannel = (CommunicationChannel) o;
    return Objects.equals(this.address, communicationChannel.address) &&
        Objects.equals(this.id, communicationChannel.id) &&
        Objects.equals(this.position, communicationChannel.position) &&
        Objects.equals(this.type, communicationChannel.type) &&
        Objects.equals(this.userId, communicationChannel.userId) &&
        Objects.equals(this.workflowState, communicationChannel.workflowState);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(address, id, position, type, userId, workflowState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommunicationChannel {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    workflowState: ").append(toIndentedString(workflowState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
