/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ContextExternalTool
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class ContextExternalTool {

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("domain")

  private String domain = null;

  @JsonProperty("url")

  private String url = null;

  @JsonProperty("consumer_key")

  private String consumerKey = null;

  @JsonProperty("name")

  private String name = null;
  public ContextExternalTool id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * The unique identifier for the tool
  * @return id
  **/
  @Schema(description = "The unique identifier for the tool")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public ContextExternalTool domain(String domain) {
    this.domain = domain;
    return this;
  }

  

  /**
  * The domain to match links against
  * @return domain
  **/
  @Schema(description = "The domain to match links against")
  public String getDomain() {
    return domain;
  }
  public void setDomain(String domain) {
    this.domain = domain;
  }
  public ContextExternalTool url(String url) {
    this.url = url;
    return this;
  }

  

  /**
  * The url to match links against
  * @return url
  **/
  @Schema(description = "The url to match links against")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }
  public ContextExternalTool consumerKey(String consumerKey) {
    this.consumerKey = consumerKey;
    return this;
  }

  

  /**
  * The consumer key used by the tool (The associated shared secret is not returned)
  * @return consumerKey
  **/
  @Schema(description = "The consumer key used by the tool (The associated shared secret is not returned)")
  public String getConsumerKey() {
    return consumerKey;
  }
  public void setConsumerKey(String consumerKey) {
    this.consumerKey = consumerKey;
  }
  public ContextExternalTool name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The name of the tool
  * @return name
  **/
  @Schema(description = "The name of the tool")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextExternalTool contextExternalTool = (ContextExternalTool) o;
    return Objects.equals(this.id, contextExternalTool.id) &&
        Objects.equals(this.domain, contextExternalTool.domain) &&
        Objects.equals(this.url, contextExternalTool.url) &&
        Objects.equals(this.consumerKey, contextExternalTool.consumerKey) &&
        Objects.equals(this.name, contextExternalTool.name);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, domain, url, consumerKey, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextExternalTool {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    consumerKey: ").append(toIndentedString(consumerKey)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
