/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Attributes of a course object.  See Courses API for more details
 */
@Schema(description = "Attributes of a course object.  See Courses API for more details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class CourseAttributes {

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("integration_id")

  private String integrationId = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("sis_id")

  private String sisId = null;
  public CourseAttributes id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * The unique Canvas identifier for the origin course
  * @return id
  **/
  @Schema(example = "7", description = "The unique Canvas identifier for the origin course")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public CourseAttributes integrationId(String integrationId) {
    this.integrationId = integrationId;
    return this;
  }

  

  /**
  * The integration ID of the origin_course.
  * @return integrationId
  **/
  @Schema(example = "I-2", description = "The integration ID of the origin_course.")
  public String getIntegrationId() {
    return integrationId;
  }
  public void setIntegrationId(String integrationId) {
    this.integrationId = integrationId;
  }
  public CourseAttributes name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The name of the origin course.
  * @return name
  **/
  @Schema(example = "Section A", description = "The name of the origin course.")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public CourseAttributes sisId(String sisId) {
    this.sisId = sisId;
    return this;
  }

  

  /**
  * The sis id of the origin_course.
  * @return sisId
  **/
  @Schema(example = "c34643", description = "The sis id of the origin_course.")
  public String getSisId() {
    return sisId;
  }
  public void setSisId(String sisId) {
    this.sisId = sisId;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CourseAttributes courseAttributes = (CourseAttributes) o;
    return Objects.equals(this.id, courseAttributes.id) &&
        Objects.equals(this.integrationId, courseAttributes.integrationId) &&
        Objects.equals(this.name, courseAttributes.name) &&
        Objects.equals(this.sisId, courseAttributes.sisId);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(id, integrationId, name, sisId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CourseAttributes {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    integrationId: ").append(toIndentedString(integrationId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sisId: ").append(toIndentedString(sisId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
