/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

/**
 * EpubExport
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class EpubExport {

  @JsonProperty("attachment")

  private java.io.File attachment = null;

  @JsonProperty("created_at")

  private OffsetDateTime createdAt = null;

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("progress_url")

  private String progressUrl = null;

  @JsonProperty("user_id")

  private Integer userId = null;

  @JsonProperty("workflow_state")

  private String workflowState = null;
  public EpubExport attachment(java.io.File attachment) {
    this.attachment = attachment;
    return this;
  }

  

  /**
  * Get attachment
  * @return attachment
  **/
  @Schema(description = "")
  public java.io.File getAttachment() {
    return attachment;
  }
  public void setAttachment(java.io.File attachment) {
    this.attachment = attachment;
  }
  public EpubExport createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  

  /**
  * the date and time this export was requested
  * @return createdAt
  **/
  @Schema(description = "the date and time this export was requested")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }
  public EpubExport id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * the unique identifier for the export
  * @return id
  **/
  @Schema(example = "101", description = "the unique identifier for the export")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public EpubExport progressUrl(String progressUrl) {
    this.progressUrl = progressUrl;
    return this;
  }

  

  /**
  * The api endpoint for polling the current progress
  * @return progressUrl
  **/
  @Schema(example = "https://example.com/api/v1/progress/4", description = "The api endpoint for polling the current progress")
  public String getProgressUrl() {
    return progressUrl;
  }
  public void setProgressUrl(String progressUrl) {
    this.progressUrl = progressUrl;
  }
  public EpubExport userId(Integer userId) {
    this.userId = userId;
    return this;
  }

  

  /**
  * The ID of the user who started the export
  * @return userId
  **/
  @Schema(example = "4", description = "The ID of the user who started the export")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }
  public EpubExport workflowState(String workflowState) {
    this.workflowState = workflowState;
    return this;
  }

  

  /**
  * Current state of the ePub export: created exporting exported generating generated failed
  * @return workflowState
  **/
  @Schema(example = "exported", description = "Current state of the ePub export: created exporting exported generating generated failed")
  public String getWorkflowState() {
    return workflowState;
  }
  public void setWorkflowState(String workflowState) {
    this.workflowState = workflowState;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EpubExport epubExport = (EpubExport) o;
    return Objects.equals(this.attachment, epubExport.attachment) &&
        Objects.equals(this.createdAt, epubExport.createdAt) &&
        Objects.equals(this.id, epubExport.id) &&
        Objects.equals(this.progressUrl, epubExport.progressUrl) &&
        Objects.equals(this.userId, epubExport.userId) &&
        Objects.equals(this.workflowState, epubExport.workflowState);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(attachment, createdAt, id, progressUrl, userId, workflowState);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EpubExport {\n");
    
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    progressUrl: ").append(toIndentedString(progressUrl)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    workflowState: ").append(toIndentedString(workflowState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
