/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * A single attribute name to be federated when a user logs in
 */
@Schema(description = "A single attribute name to be federated when a user logs in")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class FederatedAttributeConfig {

  @JsonProperty("attribute")

  private String attribute = null;

  @JsonProperty("provisioning_only")

  private Boolean provisioningOnly = null;
  public FederatedAttributeConfig attribute(String attribute) {
    this.attribute = attribute;
    return this;
  }

  

  /**
  * The name of the attribute as it will be sent from the authentication provider
  * @return attribute
  **/
  @Schema(example = "mail", description = "The name of the attribute as it will be sent from the authentication provider")
  public String getAttribute() {
    return attribute;
  }
  public void setAttribute(String attribute) {
    this.attribute = attribute;
  }
  public FederatedAttributeConfig provisioningOnly(Boolean provisioningOnly) {
    this.provisioningOnly = provisioningOnly;
    return this;
  }

  

  /**
  * If the attribute should be applied only when provisioning a new user, rather than all logins
  * @return provisioningOnly
  **/
  @Schema(example = "false", description = "If the attribute should be applied only when provisioning a new user, rather than all logins")
  public Boolean isProvisioningOnly() {
    return provisioningOnly;
  }
  public void setProvisioningOnly(Boolean provisioningOnly) {
    this.provisioningOnly = provisioningOnly;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FederatedAttributeConfig federatedAttributeConfig = (FederatedAttributeConfig) o;
    return Objects.equals(this.attribute, federatedAttributeConfig.attribute) &&
        Objects.equals(this.provisioningOnly, federatedAttributeConfig.provisioningOnly);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(attribute, provisioningOnly);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FederatedAttributeConfig {\n");
    
    sb.append("    attribute: ").append(toIndentedString(attribute)).append("\n");
    sb.append("    provisioningOnly: ").append(toIndentedString(provisioningOnly)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
