/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * A mapping of Canvas attribute names to attribute names that a provider may send, in order to update the value of these attributes when a user logs in. The values can be a FederatedAttributeConfig, or a raw string corresponding to the \&quot;attribute\&quot; property of a FederatedAttributeConfig. In responses, full FederatedAttributeConfig objects are returned if JIT provisioning is enabled, otherwise just the attribute names are returned.
 */
@Schema(description = "A mapping of Canvas attribute names to attribute names that a provider may send, in order to update the value of these attributes when a user logs in. The values can be a FederatedAttributeConfig, or a raw string corresponding to the \"attribute\" property of a FederatedAttributeConfig. In responses, full FederatedAttributeConfig objects are returned if JIT provisioning is enabled, otherwise just the attribute names are returned.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class FederatedAttributesConfig {

  @JsonProperty("admin_roles")

  private String adminRoles = null;

  @JsonProperty("display_name")

  private String displayName = null;

  @JsonProperty("email")

  private String email = null;

  @JsonProperty("given_name")

  private String givenName = null;

  @JsonProperty("integration_id")

  private String integrationId = null;

  @JsonProperty("locale")

  private String locale = null;

  @JsonProperty("name")

  private String name = null;

  @JsonProperty("sis_user_id")

  private String sisUserId = null;

  @JsonProperty("sortable_name")

  private String sortableName = null;

  @JsonProperty("surname")

  private String surname = null;

  @JsonProperty("timezone")

  private String timezone = null;
  public FederatedAttributesConfig adminRoles(String adminRoles) {
    this.adminRoles = adminRoles;
    return this;
  }

  

  /**
  * A comma separated list of role names to grant to the user. Note that these only apply at the root account level, and not sub-accounts. If the attribute is not marked for provisioning only, the user will also be removed from any other roles they currently hold that are not still specified by the IdP.
  * @return adminRoles
  **/
  @Schema(description = "A comma separated list of role names to grant to the user. Note that these only apply at the root account level, and not sub-accounts. If the attribute is not marked for provisioning only, the user will also be removed from any other roles they currently hold that are not still specified by the IdP.")
  public String getAdminRoles() {
    return adminRoles;
  }
  public void setAdminRoles(String adminRoles) {
    this.adminRoles = adminRoles;
  }
  public FederatedAttributesConfig displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

  

  /**
  * The full display name of the user
  * @return displayName
  **/
  @Schema(description = "The full display name of the user")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }
  public FederatedAttributesConfig email(String email) {
    this.email = email;
    return this;
  }

  

  /**
  * The user&#x27;s e-mail address
  * @return email
  **/
  @Schema(description = "The user's e-mail address")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }
  public FederatedAttributesConfig givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

  

  /**
  * The first, or given, name of the user
  * @return givenName
  **/
  @Schema(description = "The first, or given, name of the user")
  public String getGivenName() {
    return givenName;
  }
  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }
  public FederatedAttributesConfig integrationId(String integrationId) {
    this.integrationId = integrationId;
    return this;
  }

  

  /**
  * The secondary unique identifier for SIS purposes
  * @return integrationId
  **/
  @Schema(description = "The secondary unique identifier for SIS purposes")
  public String getIntegrationId() {
    return integrationId;
  }
  public void setIntegrationId(String integrationId) {
    this.integrationId = integrationId;
  }
  public FederatedAttributesConfig locale(String locale) {
    this.locale = locale;
    return this;
  }

  

  /**
  * The user&#x27;s preferred locale/language
  * @return locale
  **/
  @Schema(description = "The user's preferred locale/language")
  public String getLocale() {
    return locale;
  }
  public void setLocale(String locale) {
    this.locale = locale;
  }
  public FederatedAttributesConfig name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * The full name of the user
  * @return name
  **/
  @Schema(description = "The full name of the user")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public FederatedAttributesConfig sisUserId(String sisUserId) {
    this.sisUserId = sisUserId;
    return this;
  }

  

  /**
  * The unique SIS identifier
  * @return sisUserId
  **/
  @Schema(description = "The unique SIS identifier")
  public String getSisUserId() {
    return sisUserId;
  }
  public void setSisUserId(String sisUserId) {
    this.sisUserId = sisUserId;
  }
  public FederatedAttributesConfig sortableName(String sortableName) {
    this.sortableName = sortableName;
    return this;
  }

  

  /**
  * The full name of the user for sorting purposes
  * @return sortableName
  **/
  @Schema(description = "The full name of the user for sorting purposes")
  public String getSortableName() {
    return sortableName;
  }
  public void setSortableName(String sortableName) {
    this.sortableName = sortableName;
  }
  public FederatedAttributesConfig surname(String surname) {
    this.surname = surname;
    return this;
  }

  

  /**
  * The surname, or last name, of the user
  * @return surname
  **/
  @Schema(description = "The surname, or last name, of the user")
  public String getSurname() {
    return surname;
  }
  public void setSurname(String surname) {
    this.surname = surname;
  }
  public FederatedAttributesConfig timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

  

  /**
  * The user&#x27;s preferred time zone
  * @return timezone
  **/
  @Schema(description = "The user's preferred time zone")
  public String getTimezone() {
    return timezone;
  }
  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FederatedAttributesConfig federatedAttributesConfig = (FederatedAttributesConfig) o;
    return Objects.equals(this.adminRoles, federatedAttributesConfig.adminRoles) &&
        Objects.equals(this.displayName, federatedAttributesConfig.displayName) &&
        Objects.equals(this.email, federatedAttributesConfig.email) &&
        Objects.equals(this.givenName, federatedAttributesConfig.givenName) &&
        Objects.equals(this.integrationId, federatedAttributesConfig.integrationId) &&
        Objects.equals(this.locale, federatedAttributesConfig.locale) &&
        Objects.equals(this.name, federatedAttributesConfig.name) &&
        Objects.equals(this.sisUserId, federatedAttributesConfig.sisUserId) &&
        Objects.equals(this.sortableName, federatedAttributesConfig.sortableName) &&
        Objects.equals(this.surname, federatedAttributesConfig.surname) &&
        Objects.equals(this.timezone, federatedAttributesConfig.timezone);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(adminRoles, displayName, email, givenName, integrationId, locale, name, sisUserId, sortableName, surname, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FederatedAttributesConfig {\n");
    
    sb.append("    adminRoles: ").append(toIndentedString(adminRoles)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    integrationId: ").append(toIndentedString(integrationId)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sisUserId: ").append(toIndentedString(sisUserId)).append("\n");
    sb.append("    sortableName: ").append(toIndentedString(sortableName)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
