/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.instructure.canvas.model.HelpLink;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * HelpLinks
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class HelpLinks {

  @JsonProperty("custom_help_links")

  private List<HelpLink> customHelpLinks = null;

  @JsonProperty("default_help_links")

  private List<HelpLink> defaultHelpLinks = null;

  @JsonProperty("help_link_icon")

  private String helpLinkIcon = null;

  @JsonProperty("help_link_name")

  private String helpLinkName = null;
  public HelpLinks customHelpLinks(List<HelpLink> customHelpLinks) {
    this.customHelpLinks = customHelpLinks;
    return this;
  }

  public HelpLinks addCustomHelpLinksItem(HelpLink customHelpLinksItem) {
    if (this.customHelpLinks == null) {
      this.customHelpLinks = new ArrayList<HelpLink>();
    }
    this.customHelpLinks.add(customHelpLinksItem);
    return this;
  }

  /**
  * Help links defined by the account. Could include default help links.
  * @return customHelpLinks
  **/
  @Schema(example = "[{available_to=[user, student, teacher, admin, observer, unenrolled], id=link1, subtext=Something something., text=Custom Link!, type=custom, url=https://google.com}]", description = "Help links defined by the account. Could include default help links.")
  public List<HelpLink> getCustomHelpLinks() {
    return customHelpLinks;
  }
  public void setCustomHelpLinks(List<HelpLink> customHelpLinks) {
    this.customHelpLinks = customHelpLinks;
  }
  public HelpLinks defaultHelpLinks(List<HelpLink> defaultHelpLinks) {
    this.defaultHelpLinks = defaultHelpLinks;
    return this;
  }

  public HelpLinks addDefaultHelpLinksItem(HelpLink defaultHelpLinksItem) {
    if (this.defaultHelpLinks == null) {
      this.defaultHelpLinks = new ArrayList<HelpLink>();
    }
    this.defaultHelpLinks.add(defaultHelpLinksItem);
    return this;
  }

  /**
  * Default help links provided when account has not set help links of their own.
  * @return defaultHelpLinks
  **/
  @Schema(example = "[{available_to=[student], id=instructor_question, subtext=Questions are submitted to your instructor, text=Ask Your Instructor a Question, type=default, url=#teacher_feedback}, {available_to=[user, student, teacher, admin, observer, unenrolled], id=search_the_canvas_guides, subtext=Find answers to common questions, text=Search the Canvas Guides, type=default, url=http://community.canvaslms.com/community/answers/guides}, {available_to=[user, student, teacher, admin, observer, unenrolled], id=report_a_problem, subtext=If Canvas misbehaves, tell us about it, text=Report a Problem, type=default, url=#create_ticket}]", description = "Default help links provided when account has not set help links of their own.")
  public List<HelpLink> getDefaultHelpLinks() {
    return defaultHelpLinks;
  }
  public void setDefaultHelpLinks(List<HelpLink> defaultHelpLinks) {
    this.defaultHelpLinks = defaultHelpLinks;
  }
  public HelpLinks helpLinkIcon(String helpLinkIcon) {
    this.helpLinkIcon = helpLinkIcon;
    return this;
  }

  

  /**
  * Help link button icon
  * @return helpLinkIcon
  **/
  @Schema(example = "help", description = "Help link button icon")
  public String getHelpLinkIcon() {
    return helpLinkIcon;
  }
  public void setHelpLinkIcon(String helpLinkIcon) {
    this.helpLinkIcon = helpLinkIcon;
  }
  public HelpLinks helpLinkName(String helpLinkName) {
    this.helpLinkName = helpLinkName;
    return this;
  }

  

  /**
  * Help link button title
  * @return helpLinkName
  **/
  @Schema(example = "Help And Policies", description = "Help link button title")
  public String getHelpLinkName() {
    return helpLinkName;
  }
  public void setHelpLinkName(String helpLinkName) {
    this.helpLinkName = helpLinkName;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HelpLinks helpLinks = (HelpLinks) o;
    return Objects.equals(this.customHelpLinks, helpLinks.customHelpLinks) &&
        Objects.equals(this.defaultHelpLinks, helpLinks.defaultHelpLinks) &&
        Objects.equals(this.helpLinkIcon, helpLinks.helpLinkIcon) &&
        Objects.equals(this.helpLinkName, helpLinks.helpLinkName);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(customHelpLinks, defaultHelpLinks, helpLinkIcon, helpLinkName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HelpLinks {\n");
    
    sb.append("    customHelpLinks: ").append(toIndentedString(customHelpLinks)).append("\n");
    sb.append("    defaultHelpLinks: ").append(toIndentedString(defaultHelpLinks)).append("\n");
    sb.append("    helpLinkIcon: ").append(toIndentedString(helpLinkIcon)).append("\n");
    sb.append("    helpLinkName: ").append(toIndentedString(helpLinkName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
