/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.instructure.canvas.model.OutcomeGroup;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * OutcomeGroup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class OutcomeGroup {

  @JsonProperty("can_edit")

  private Boolean canEdit = null;

  @JsonProperty("context_id")

  private Integer contextId = null;

  @JsonProperty("context_type")

  private String contextType = null;

  @JsonProperty("description")

  private String description = null;

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("import_url")

  private String importUrl = null;

  @JsonProperty("outcomes_url")

  private String outcomesUrl = null;

  @JsonProperty("parent_outcome_group")

  private OutcomeGroup parentOutcomeGroup = null;

  @JsonProperty("subgroups_url")

  private String subgroupsUrl = null;

  @JsonProperty("title")

  private String title = null;

  @JsonProperty("url")

  private String url = null;

  @JsonProperty("vendor_guid")

  private String vendorGuid = null;
  public OutcomeGroup canEdit(Boolean canEdit) {
    this.canEdit = canEdit;
    return this;
  }

  

  /**
  * whether the current user can update the outcome group
  * @return canEdit
  **/
  @Schema(example = "true", description = "whether the current user can update the outcome group")
  public Boolean isCanEdit() {
    return canEdit;
  }
  public void setCanEdit(Boolean canEdit) {
    this.canEdit = canEdit;
  }
  public OutcomeGroup contextId(Integer contextId) {
    this.contextId = contextId;
    return this;
  }

  

  /**
  * the context owning the outcome group. may be null for global outcome groups. omitted in the abbreviated form.
  * @return contextId
  **/
  @Schema(example = "1", description = "the context owning the outcome group. may be null for global outcome groups. omitted in the abbreviated form.")
  public Integer getContextId() {
    return contextId;
  }
  public void setContextId(Integer contextId) {
    this.contextId = contextId;
  }
  public OutcomeGroup contextType(String contextType) {
    this.contextType = contextType;
    return this;
  }

  

  /**
  * Get contextType
  * @return contextType
  **/
  @Schema(example = "Account", description = "")
  public String getContextType() {
    return contextType;
  }
  public void setContextType(String contextType) {
    this.contextType = contextType;
  }
  public OutcomeGroup description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * description of the outcome group. omitted in the abbreviated form.
  * @return description
  **/
  @Schema(example = "Outcome group description", description = "description of the outcome group. omitted in the abbreviated form.")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public OutcomeGroup id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * the ID of the outcome group
  * @return id
  **/
  @Schema(example = "1", description = "the ID of the outcome group")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public OutcomeGroup importUrl(String importUrl) {
    this.importUrl = importUrl;
    return this;
  }

  

  /**
  * the URL for importing another group into this outcome group. should be treated as opaque. omitted in the abbreviated form.
  * @return importUrl
  **/
  @Schema(example = "/api/v1/accounts/1/outcome_groups/1/import", description = "the URL for importing another group into this outcome group. should be treated as opaque. omitted in the abbreviated form.")
  public String getImportUrl() {
    return importUrl;
  }
  public void setImportUrl(String importUrl) {
    this.importUrl = importUrl;
  }
  public OutcomeGroup outcomesUrl(String outcomesUrl) {
    this.outcomesUrl = outcomesUrl;
    return this;
  }

  

  /**
  * the URL for listing/creating outcome links under the outcome group. should be treated as opaque
  * @return outcomesUrl
  **/
  @Schema(example = "/api/v1/accounts/1/outcome_groups/1/outcomes", description = "the URL for listing/creating outcome links under the outcome group. should be treated as opaque")
  public String getOutcomesUrl() {
    return outcomesUrl;
  }
  public void setOutcomesUrl(String outcomesUrl) {
    this.outcomesUrl = outcomesUrl;
  }
  public OutcomeGroup parentOutcomeGroup(OutcomeGroup parentOutcomeGroup) {
    this.parentOutcomeGroup = parentOutcomeGroup;
    return this;
  }

  

  /**
  * Get parentOutcomeGroup
  * @return parentOutcomeGroup
  **/
  @Schema(description = "")
  public OutcomeGroup getParentOutcomeGroup() {
    return parentOutcomeGroup;
  }
  public void setParentOutcomeGroup(OutcomeGroup parentOutcomeGroup) {
    this.parentOutcomeGroup = parentOutcomeGroup;
  }
  public OutcomeGroup subgroupsUrl(String subgroupsUrl) {
    this.subgroupsUrl = subgroupsUrl;
    return this;
  }

  

  /**
  * the URL for listing/creating subgroups under the outcome group. should be treated as opaque
  * @return subgroupsUrl
  **/
  @Schema(example = "/api/v1/accounts/1/outcome_groups/1/subgroups", description = "the URL for listing/creating subgroups under the outcome group. should be treated as opaque")
  public String getSubgroupsUrl() {
    return subgroupsUrl;
  }
  public void setSubgroupsUrl(String subgroupsUrl) {
    this.subgroupsUrl = subgroupsUrl;
  }
  public OutcomeGroup title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * title of the outcome group
  * @return title
  **/
  @Schema(example = "Outcome group title", description = "title of the outcome group")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public OutcomeGroup url(String url) {
    this.url = url;
    return this;
  }

  

  /**
  * the URL for fetching/updating the outcome group. should be treated as opaque
  * @return url
  **/
  @Schema(example = "/api/v1/accounts/1/outcome_groups/1", description = "the URL for fetching/updating the outcome group. should be treated as opaque")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }
  public OutcomeGroup vendorGuid(String vendorGuid) {
    this.vendorGuid = vendorGuid;
    return this;
  }

  

  /**
  * A custom GUID for the learning standard.
  * @return vendorGuid
  **/
  @Schema(example = "customid9000", description = "A custom GUID for the learning standard.")
  public String getVendorGuid() {
    return vendorGuid;
  }
  public void setVendorGuid(String vendorGuid) {
    this.vendorGuid = vendorGuid;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutcomeGroup outcomeGroup = (OutcomeGroup) o;
    return Objects.equals(this.canEdit, outcomeGroup.canEdit) &&
        Objects.equals(this.contextId, outcomeGroup.contextId) &&
        Objects.equals(this.contextType, outcomeGroup.contextType) &&
        Objects.equals(this.description, outcomeGroup.description) &&
        Objects.equals(this.id, outcomeGroup.id) &&
        Objects.equals(this.importUrl, outcomeGroup.importUrl) &&
        Objects.equals(this.outcomesUrl, outcomeGroup.outcomesUrl) &&
        Objects.equals(this.parentOutcomeGroup, outcomeGroup.parentOutcomeGroup) &&
        Objects.equals(this.subgroupsUrl, outcomeGroup.subgroupsUrl) &&
        Objects.equals(this.title, outcomeGroup.title) &&
        Objects.equals(this.url, outcomeGroup.url) &&
        Objects.equals(this.vendorGuid, outcomeGroup.vendorGuid);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(canEdit, contextId, contextType, description, id, importUrl, outcomesUrl, parentOutcomeGroup, subgroupsUrl, title, url, vendorGuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutcomeGroup {\n");
    
    sb.append("    canEdit: ").append(toIndentedString(canEdit)).append("\n");
    sb.append("    contextId: ").append(toIndentedString(contextId)).append("\n");
    sb.append("    contextType: ").append(toIndentedString(contextType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    importUrl: ").append(toIndentedString(importUrl)).append("\n");
    sb.append("    outcomesUrl: ").append(toIndentedString(outcomesUrl)).append("\n");
    sb.append("    parentOutcomeGroup: ").append(toIndentedString(parentOutcomeGroup)).append("\n");
    sb.append("    subgroupsUrl: ").append(toIndentedString(subgroupsUrl)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    vendorGuid: ").append(toIndentedString(vendorGuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
