/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * OutcomeAlignment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class OutcomeAlignment {

  @JsonProperty("assignment_id")

  private Integer assignmentId = null;

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("submission_types")

  private String submissionTypes = null;

  @JsonProperty("title")

  private String title = null;

  @JsonProperty("url")

  private String url = null;
  public OutcomeAlignment assignmentId(Integer assignmentId) {
    this.assignmentId = assignmentId;
    return this;
  }

  

  /**
  * the id of the aligned assignment.
  * @return assignmentId
  **/
  @Schema(example = "2", description = "the id of the aligned assignment.")
  public Integer getAssignmentId() {
    return assignmentId;
  }
  public void setAssignmentId(Integer assignmentId) {
    this.assignmentId = assignmentId;
  }
  public OutcomeAlignment id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * the id of the aligned learning outcome.
  * @return id
  **/
  @Schema(example = "1", description = "the id of the aligned learning outcome.")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public OutcomeAlignment submissionTypes(String submissionTypes) {
    this.submissionTypes = submissionTypes;
    return this;
  }

  

  /**
  * a string representing the different submission types of an aligned assignment.
  * @return submissionTypes
  **/
  @Schema(example = "online_text_entry,online_url", description = "a string representing the different submission types of an aligned assignment.")
  public String getSubmissionTypes() {
    return submissionTypes;
  }
  public void setSubmissionTypes(String submissionTypes) {
    this.submissionTypes = submissionTypes;
  }
  public OutcomeAlignment title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * the title of the aligned assignment.
  * @return title
  **/
  @Schema(example = "Unit 1 test", description = "the title of the aligned assignment.")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public OutcomeAlignment url(String url) {
    this.url = url;
    return this;
  }

  

  /**
  * the URL for the aligned assignment.
  * @return url
  **/
  @Schema(example = "/courses/1/assignments/5", description = "the URL for the aligned assignment.")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutcomeAlignment outcomeAlignment = (OutcomeAlignment) o;
    return Objects.equals(this.assignmentId, outcomeAlignment.assignmentId) &&
        Objects.equals(this.id, outcomeAlignment.id) &&
        Objects.equals(this.submissionTypes, outcomeAlignment.submissionTypes) &&
        Objects.equals(this.title, outcomeAlignment.title) &&
        Objects.equals(this.url, outcomeAlignment.url);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(assignmentId, id, submissionTypes, title, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutcomeAlignment {\n");
    
    sb.append("    assignmentId: ").append(toIndentedString(assignmentId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    submissionTypes: ").append(toIndentedString(submissionTypes)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
