/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

/**
 * Poll
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class Poll {

  @JsonProperty("created_at")

  private OffsetDateTime createdAt = null;

  @JsonProperty("description")

  private String description = null;

  @JsonProperty("id")

  private Integer id = null;

  @JsonProperty("question")

  private String question = null;

  @JsonProperty("total_results")

  private Object totalResults = null;

  @JsonProperty("user_id")

  private Integer userId = null;
  public Poll createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  

  /**
  * The time at which the poll was created.
  * @return createdAt
  **/
  @Schema(description = "The time at which the poll was created.")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }
  public Poll description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * A short description of the poll.
  * @return description
  **/
  @Schema(example = "This poll is to determine what priorities the students in the course have.", description = "A short description of the poll.")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public Poll id(Integer id) {
    this.id = id;
    return this;
  }

  

  /**
  * The unique identifier for the poll.
  * @return id
  **/
  @Schema(example = "1023", required = true, description = "The unique identifier for the poll.")
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public Poll question(String question) {
    this.question = question;
    return this;
  }

  

  /**
  * The question/title of the poll.
  * @return question
  **/
  @Schema(example = "What do you consider most important to your learning in this course?", required = true, description = "The question/title of the poll.")
  public String getQuestion() {
    return question;
  }
  public void setQuestion(String question) {
    this.question = question;
  }
  public Poll totalResults(Object totalResults) {
    this.totalResults = totalResults;
    return this;
  }

  

  /**
  * An aggregate of the results of all associated poll sessions, with the poll choice id as the key, and the aggregated submission count as the value.
  * @return totalResults
  **/
  @Schema(example = "{\"543\":20,\"544\":5,\"545\":17}", description = "An aggregate of the results of all associated poll sessions, with the poll choice id as the key, and the aggregated submission count as the value.")
  public Object getTotalResults() {
    return totalResults;
  }
  public void setTotalResults(Object totalResults) {
    this.totalResults = totalResults;
  }
  public Poll userId(Integer userId) {
    this.userId = userId;
    return this;
  }

  

  /**
  * The unique identifier for the user that created the poll.
  * @return userId
  **/
  @Schema(example = "105", description = "The unique identifier for the user that created the poll.")
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Poll poll = (Poll) o;
    return Objects.equals(this.createdAt, poll.createdAt) &&
        Objects.equals(this.description, poll.description) &&
        Objects.equals(this.id, poll.id) &&
        Objects.equals(this.question, poll.question) &&
        Objects.equals(this.totalResults, poll.totalResults) &&
        Objects.equals(this.userId, poll.userId);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(createdAt, description, id, question, totalResults, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Poll {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
