/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;

/**
 * Proficiency
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class Proficiency {

  @JsonProperty("ratings")

  private List<Object> ratings = null;
  public Proficiency ratings(List<Object> ratings) {
    this.ratings = ratings;
    return this;
  }

  public Proficiency addRatingsItem(Object ratingsItem) {
    if (this.ratings == null) {
      this.ratings = new ArrayList<Object>();
    }
    this.ratings.add(ratingsItem);
    return this;
  }

  /**
  * An array of proficiency ratings. See the ProficiencyRating specification above.
  * @return ratings
  **/
  @Schema(example = "[]", description = "An array of proficiency ratings. See the ProficiencyRating specification above.")
  public List<Object> getRatings() {
    return ratings;
  }
  public void setRatings(List<Object> ratings) {
    this.ratings = ratings;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Proficiency proficiency = (Proficiency) o;
    return Objects.equals(this.ratings, proficiency.ratings);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(ratings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Proficiency {\n");
    
    sb.append("    ratings: ").append(toIndentedString(ratings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
