/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.instructure.canvas.model.QuizStatisticsAnswerStatistics;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Statistics for submissions made to a specific quiz question.
 */
@Schema(description = "Statistics for submissions made to a specific quiz question.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class QuizStatisticsQuestionStatistics {

  @JsonProperty("responses")

  private Long responses = null;

  @JsonProperty("answers")

  private QuizStatisticsAnswerStatistics answers = null;
  public QuizStatisticsQuestionStatistics responses(Long responses) {
    this.responses = responses;
    return this;
  }

  

  /**
  * Number of students who have provided an answer to this question. Blank or empty responses are not counted.
  * @return responses
  **/
  @Schema(example = "3", description = "Number of students who have provided an answer to this question. Blank or empty responses are not counted.")
  public Long getResponses() {
    return responses;
  }
  public void setResponses(Long responses) {
    this.responses = responses;
  }
  public QuizStatisticsQuestionStatistics answers(QuizStatisticsAnswerStatistics answers) {
    this.answers = answers;
    return this;
  }

  

  /**
  * Get answers
  * @return answers
  **/
  @Schema(description = "")
  public QuizStatisticsAnswerStatistics getAnswers() {
    return answers;
  }
  public void setAnswers(QuizStatisticsAnswerStatistics answers) {
    this.answers = answers;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuizStatisticsQuestionStatistics quizStatisticsQuestionStatistics = (QuizStatisticsQuestionStatistics) o;
    return Objects.equals(this.responses, quizStatisticsQuestionStatistics.responses) &&
        Objects.equals(this.answers, quizStatisticsQuestionStatistics.answers);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(responses, answers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuizStatisticsQuestionStatistics {\n");
    
    sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
    sb.append("    answers: ").append(toIndentedString(answers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
