/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;

/**
 * A point-biserial construct for a single pre-defined answer in a Multiple-Choice or True/False question.
 */
@Schema(description = "A point-biserial construct for a single pre-defined answer in a Multiple-Choice or True/False question.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class QuizStatisticsAnswerPointBiserial {

  @JsonProperty("answer_id")

  private Long answerId = null;

  @JsonProperty("correct")

  private Boolean correct = null;

  @JsonProperty("distractor")

  private Boolean distractor = null;

  @JsonProperty("point_biserial")

  private BigDecimal pointBiserial = null;
  public QuizStatisticsAnswerPointBiserial answerId(Long answerId) {
    this.answerId = answerId;
    return this;
  }

  

  /**
  * ID of the answer the point biserial is for.
  * @return answerId
  **/
  @Schema(example = "3866", description = "ID of the answer the point biserial is for.")
  public Long getAnswerId() {
    return answerId;
  }
  public void setAnswerId(Long answerId) {
    this.answerId = answerId;
  }
  public QuizStatisticsAnswerPointBiserial correct(Boolean correct) {
    this.correct = correct;
    return this;
  }

  

  /**
  * Convenience attribute that denotes whether this is the correct answer as opposed to being a distractor. This is mutually exclusive with the &#x60;distractor&#x60; value
  * @return correct
  **/
  @Schema(example = "true", description = "Convenience attribute that denotes whether this is the correct answer as opposed to being a distractor. This is mutually exclusive with the `distractor` value")
  public Boolean isCorrect() {
    return correct;
  }
  public void setCorrect(Boolean correct) {
    this.correct = correct;
  }
  public QuizStatisticsAnswerPointBiserial distractor(Boolean distractor) {
    this.distractor = distractor;
    return this;
  }

  

  /**
  * Convenience attribute that denotes whether this is a distractor answer and not the correct one. This is mutually exclusive with the &#x60;correct&#x60; value
  * @return distractor
  **/
  @Schema(example = "false", description = "Convenience attribute that denotes whether this is a distractor answer and not the correct one. This is mutually exclusive with the `correct` value")
  public Boolean isDistractor() {
    return distractor;
  }
  public void setDistractor(Boolean distractor) {
    this.distractor = distractor;
  }
  public QuizStatisticsAnswerPointBiserial pointBiserial(BigDecimal pointBiserial) {
    this.pointBiserial = pointBiserial;
    return this;
  }

  

  /**
  * The point biserial value for this answer. Value ranges between -1 and 1.
  * @return pointBiserial
  **/
  @Schema(example = "-0.802955068546966", description = "The point biserial value for this answer. Value ranges between -1 and 1.")
  public BigDecimal getPointBiserial() {
    return pointBiserial;
  }
  public void setPointBiserial(BigDecimal pointBiserial) {
    this.pointBiserial = pointBiserial;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuizStatisticsAnswerPointBiserial quizStatisticsAnswerPointBiserial = (QuizStatisticsAnswerPointBiserial) o;
    return Objects.equals(this.answerId, quizStatisticsAnswerPointBiserial.answerId) &&
        Objects.equals(this.correct, quizStatisticsAnswerPointBiserial.correct) &&
        Objects.equals(this.distractor, quizStatisticsAnswerPointBiserial.distractor) &&
        Objects.equals(this.pointBiserial, quizStatisticsAnswerPointBiserial.pointBiserial);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(answerId, correct, distractor, pointBiserial);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuizStatisticsAnswerPointBiserial {\n");
    
    sb.append("    answerId: ").append(toIndentedString(answerId)).append("\n");
    sb.append("    correct: ").append(toIndentedString(correct)).append("\n");
    sb.append("    distractor: ").append(toIndentedString(distractor)).append("\n");
    sb.append("    pointBiserial: ").append(toIndentedString(pointBiserial)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
