/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Scope
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class Scope {

  @JsonProperty("action")

  private String action = null;

  @JsonProperty("controller")

  private String controller = null;

  @JsonProperty("resource")

  private String resource = null;

  @JsonProperty("resource_name")

  private String resourceName = null;

  @JsonProperty("scope")

  private String scope = null;

  @JsonProperty("verb")

  private String verb = null;
  public Scope action(String action) {
    this.action = action;
    return this;
  }

  

  /**
  * The controller action the scope is associated to
  * @return action
  **/
  @Schema(example = "index", description = "The controller action the scope is associated to")
  public String getAction() {
    return action;
  }
  public void setAction(String action) {
    this.action = action;
  }
  public Scope controller(String controller) {
    this.controller = controller;
    return this;
  }

  

  /**
  * The controller the scope is associated to
  * @return controller
  **/
  @Schema(example = "courses", description = "The controller the scope is associated to")
  public String getController() {
    return controller;
  }
  public void setController(String controller) {
    this.controller = controller;
  }
  public Scope resource(String resource) {
    this.resource = resource;
    return this;
  }

  

  /**
  * The resource the scope is associated with
  * @return resource
  **/
  @Schema(example = "courses", description = "The resource the scope is associated with")
  public String getResource() {
    return resource;
  }
  public void setResource(String resource) {
    this.resource = resource;
  }
  public Scope resourceName(String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  

  /**
  * The localized resource name
  * @return resourceName
  **/
  @Schema(example = "Courses", description = "The localized resource name")
  public String getResourceName() {
    return resourceName;
  }
  public void setResourceName(String resourceName) {
    this.resourceName = resourceName;
  }
  public Scope scope(String scope) {
    this.scope = scope;
    return this;
  }

  

  /**
  * The identifier for the scope
  * @return scope
  **/
  @Schema(example = "url:GET|/api/v1/courses", description = "The identifier for the scope")
  public String getScope() {
    return scope;
  }
  public void setScope(String scope) {
    this.scope = scope;
  }
  public Scope verb(String verb) {
    this.verb = verb;
    return this;
  }

  

  /**
  * The HTTP verb for the scope
  * @return verb
  **/
  @Schema(example = "GET", description = "The HTTP verb for the scope")
  public String getVerb() {
    return verb;
  }
  public void setVerb(String verb) {
    this.verb = verb;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scope scope = (Scope) o;
    return Objects.equals(this.action, scope.action) &&
        Objects.equals(this.controller, scope.controller) &&
        Objects.equals(this.resource, scope.resource) &&
        Objects.equals(this.resourceName, scope.resourceName) &&
        Objects.equals(this.scope, scope.scope) &&
        Objects.equals(this.verb, scope.verb);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(action, controller, resource, resourceName, scope, verb);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scope {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    controller: ").append(toIndentedString(controller)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    verb: ").append(toIndentedString(verb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
