/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

/**
 * Attributes of an assignment override that apply to the section object.  See Assignments API for more details
 */
@Schema(description = "Attributes of an assignment override that apply to the section object.  See Assignments API for more details")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class SectionAssignmentOverrideAttributes {

  @JsonProperty("due_at")

  private OffsetDateTime dueAt = null;

  @JsonProperty("lock_at")

  private OffsetDateTime lockAt = null;

  @JsonProperty("override_title")

  private String overrideTitle = null;

  @JsonProperty("unlock_at")

  private OffsetDateTime unlockAt = null;
  public SectionAssignmentOverrideAttributes dueAt(OffsetDateTime dueAt) {
    this.dueAt = dueAt;
    return this;
  }

  

  /**
  * the due date for the assignment. returns null if not present. NOTE: If this assignment has assignment overrides, this field will be the due date as it applies to the user requesting information from the API.
  * @return dueAt
  **/
  @Schema(description = "the due date for the assignment. returns null if not present. NOTE: If this assignment has assignment overrides, this field will be the due date as it applies to the user requesting information from the API.")
  public OffsetDateTime getDueAt() {
    return dueAt;
  }
  public void setDueAt(OffsetDateTime dueAt) {
    this.dueAt = dueAt;
  }
  public SectionAssignmentOverrideAttributes lockAt(OffsetDateTime lockAt) {
    this.lockAt = lockAt;
    return this;
  }

  

  /**
  * (Optional) Time at which this was/will be locked.
  * @return lockAt
  **/
  @Schema(description = "(Optional) Time at which this was/will be locked.")
  public OffsetDateTime getLockAt() {
    return lockAt;
  }
  public void setLockAt(OffsetDateTime lockAt) {
    this.lockAt = lockAt;
  }
  public SectionAssignmentOverrideAttributes overrideTitle(String overrideTitle) {
    this.overrideTitle = overrideTitle;
    return this;
  }

  

  /**
  * The title for the assignment override
  * @return overrideTitle
  **/
  @Schema(example = "some section override", description = "The title for the assignment override")
  public String getOverrideTitle() {
    return overrideTitle;
  }
  public void setOverrideTitle(String overrideTitle) {
    this.overrideTitle = overrideTitle;
  }
  public SectionAssignmentOverrideAttributes unlockAt(OffsetDateTime unlockAt) {
    this.unlockAt = unlockAt;
    return this;
  }

  

  /**
  * (Optional) Time at which this was/will be unlocked.
  * @return unlockAt
  **/
  @Schema(description = "(Optional) Time at which this was/will be unlocked.")
  public OffsetDateTime getUnlockAt() {
    return unlockAt;
  }
  public void setUnlockAt(OffsetDateTime unlockAt) {
    this.unlockAt = unlockAt;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SectionAssignmentOverrideAttributes sectionAssignmentOverrideAttributes = (SectionAssignmentOverrideAttributes) o;
    return Objects.equals(this.dueAt, sectionAssignmentOverrideAttributes.dueAt) &&
        Objects.equals(this.lockAt, sectionAssignmentOverrideAttributes.lockAt) &&
        Objects.equals(this.overrideTitle, sectionAssignmentOverrideAttributes.overrideTitle) &&
        Objects.equals(this.unlockAt, sectionAssignmentOverrideAttributes.unlockAt);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(dueAt, lockAt, overrideTitle, unlockAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SectionAssignmentOverrideAttributes {\n");
    
    sb.append("    dueAt: ").append(toIndentedString(dueAt)).append("\n");
    sb.append("    lockAt: ").append(toIndentedString(lockAt)).append("\n");
    sb.append("    overrideTitle: ").append(toIndentedString(overrideTitle)).append("\n");
    sb.append("    unlockAt: ").append(toIndentedString(unlockAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
