/*
 * canvas.instructure.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.instructure.canvas.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * TurnitinSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-11-06T15:34:49.014533Z[Europe/London]")
public class TurnitinSettings {

  @JsonProperty("exclude_biblio")

  private Boolean excludeBiblio = null;

  @JsonProperty("exclude_quoted")

  private Boolean excludeQuoted = null;

  @JsonProperty("exclude_small_matches_type")

  private String excludeSmallMatchesType = null;

  @JsonProperty("exclude_small_matches_value")

  private Integer excludeSmallMatchesValue = null;

  @JsonProperty("internet_check")

  private Boolean internetCheck = null;

  @JsonProperty("journal_check")

  private Boolean journalCheck = null;

  @JsonProperty("originality_report_visibility")

  private String originalityReportVisibility = null;

  @JsonProperty("s_paper_check")

  private Boolean sPaperCheck = null;
  public TurnitinSettings excludeBiblio(Boolean excludeBiblio) {
    this.excludeBiblio = excludeBiblio;
    return this;
  }

  

  /**
  * Get excludeBiblio
  * @return excludeBiblio
  **/
  @Schema(example = "false", description = "")
  public Boolean isExcludeBiblio() {
    return excludeBiblio;
  }
  public void setExcludeBiblio(Boolean excludeBiblio) {
    this.excludeBiblio = excludeBiblio;
  }
  public TurnitinSettings excludeQuoted(Boolean excludeQuoted) {
    this.excludeQuoted = excludeQuoted;
    return this;
  }

  

  /**
  * Get excludeQuoted
  * @return excludeQuoted
  **/
  @Schema(example = "false", description = "")
  public Boolean isExcludeQuoted() {
    return excludeQuoted;
  }
  public void setExcludeQuoted(Boolean excludeQuoted) {
    this.excludeQuoted = excludeQuoted;
  }
  public TurnitinSettings excludeSmallMatchesType(String excludeSmallMatchesType) {
    this.excludeSmallMatchesType = excludeSmallMatchesType;
    return this;
  }

  

  /**
  * Get excludeSmallMatchesType
  * @return excludeSmallMatchesType
  **/
  @Schema(example = "percent", description = "")
  public String getExcludeSmallMatchesType() {
    return excludeSmallMatchesType;
  }
  public void setExcludeSmallMatchesType(String excludeSmallMatchesType) {
    this.excludeSmallMatchesType = excludeSmallMatchesType;
  }
  public TurnitinSettings excludeSmallMatchesValue(Integer excludeSmallMatchesValue) {
    this.excludeSmallMatchesValue = excludeSmallMatchesValue;
    return this;
  }

  

  /**
  * Get excludeSmallMatchesValue
  * @return excludeSmallMatchesValue
  **/
  @Schema(example = "50", description = "")
  public Integer getExcludeSmallMatchesValue() {
    return excludeSmallMatchesValue;
  }
  public void setExcludeSmallMatchesValue(Integer excludeSmallMatchesValue) {
    this.excludeSmallMatchesValue = excludeSmallMatchesValue;
  }
  public TurnitinSettings internetCheck(Boolean internetCheck) {
    this.internetCheck = internetCheck;
    return this;
  }

  

  /**
  * Get internetCheck
  * @return internetCheck
  **/
  @Schema(example = "false", description = "")
  public Boolean isInternetCheck() {
    return internetCheck;
  }
  public void setInternetCheck(Boolean internetCheck) {
    this.internetCheck = internetCheck;
  }
  public TurnitinSettings journalCheck(Boolean journalCheck) {
    this.journalCheck = journalCheck;
    return this;
  }

  

  /**
  * Get journalCheck
  * @return journalCheck
  **/
  @Schema(example = "false", description = "")
  public Boolean isJournalCheck() {
    return journalCheck;
  }
  public void setJournalCheck(Boolean journalCheck) {
    this.journalCheck = journalCheck;
  }
  public TurnitinSettings originalityReportVisibility(String originalityReportVisibility) {
    this.originalityReportVisibility = originalityReportVisibility;
    return this;
  }

  

  /**
  * Get originalityReportVisibility
  * @return originalityReportVisibility
  **/
  @Schema(example = "after_grading", description = "")
  public String getOriginalityReportVisibility() {
    return originalityReportVisibility;
  }
  public void setOriginalityReportVisibility(String originalityReportVisibility) {
    this.originalityReportVisibility = originalityReportVisibility;
  }
  public TurnitinSettings sPaperCheck(Boolean sPaperCheck) {
    this.sPaperCheck = sPaperCheck;
    return this;
  }

  

  /**
  * Get sPaperCheck
  * @return sPaperCheck
  **/
  @Schema(example = "false", description = "")
  public Boolean isSPaperCheck() {
    return sPaperCheck;
  }
  public void setSPaperCheck(Boolean sPaperCheck) {
    this.sPaperCheck = sPaperCheck;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TurnitinSettings turnitinSettings = (TurnitinSettings) o;
    return Objects.equals(this.excludeBiblio, turnitinSettings.excludeBiblio) &&
        Objects.equals(this.excludeQuoted, turnitinSettings.excludeQuoted) &&
        Objects.equals(this.excludeSmallMatchesType, turnitinSettings.excludeSmallMatchesType) &&
        Objects.equals(this.excludeSmallMatchesValue, turnitinSettings.excludeSmallMatchesValue) &&
        Objects.equals(this.internetCheck, turnitinSettings.internetCheck) &&
        Objects.equals(this.journalCheck, turnitinSettings.journalCheck) &&
        Objects.equals(this.originalityReportVisibility, turnitinSettings.originalityReportVisibility) &&
        Objects.equals(this.sPaperCheck, turnitinSettings.sPaperCheck);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(excludeBiblio, excludeQuoted, excludeSmallMatchesType, excludeSmallMatchesValue, internetCheck, journalCheck, originalityReportVisibility, sPaperCheck);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TurnitinSettings {\n");
    
    sb.append("    excludeBiblio: ").append(toIndentedString(excludeBiblio)).append("\n");
    sb.append("    excludeQuoted: ").append(toIndentedString(excludeQuoted)).append("\n");
    sb.append("    excludeSmallMatchesType: ").append(toIndentedString(excludeSmallMatchesType)).append("\n");
    sb.append("    excludeSmallMatchesValue: ").append(toIndentedString(excludeSmallMatchesValue)).append("\n");
    sb.append("    internetCheck: ").append(toIndentedString(internetCheck)).append("\n");
    sb.append("    journalCheck: ").append(toIndentedString(journalCheck)).append("\n");
    sb.append("    originalityReportVisibility: ").append(toIndentedString(originalityReportVisibility)).append("\n");
    sb.append("    sPaperCheck: ").append(toIndentedString(sPaperCheck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
